//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int Automobile_ID { get; set; }
        public int Buyer_id { get; set; }
        public string login { get; set; }
        public string gender { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
    
        public virtual Automobile Automobile { get; set; }
        public virtual Buyer Buyer { get; set; }
    }
}
