//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_automobile
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int Automobile_ID { get; set; }
        public int Employee_ID { get; set; }
        public int Buyer_ID { get; set; }
    
        public virtual Automobile Automobile { get; set; }
        public virtual Buyer Buyer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
